### ISSUE TITLE
Activating conda environment

### ISSUE THREAD

**Issue by sylestiel** [JGASmits/AnanseSeurat#31]
@JGASmits @Rebecza @Arts-of-coding 
How to determine if the program is running or if it has stalled, "Conda activate" hangs.

Is there any way to check for it without interrupting the run if it is actually active?

Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
[Fri Sep  8 16:50:32 2023]
Finished job 5.
1 of 24 steps (4%) done
Select jobs to execute...

[Fri Sep  8 16:50:32 2023]
rule pfmscorefile:
    input: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/Peak_Counts.tsv, /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/mm10.gimme.vertebrate.v5.0.pfm, /Users/pediatrics/Desktop/R_projects/scANANSE/data/mm10
    output: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/pfmscorefile.tsv
    log: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_mm10_pfmscorefile.txt
    jobid: 6
    reason: Missing output files: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/pfmscorefile.tsv; Input files updated by another job: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/mm10.gimme.vertebrate.v5.0.pfm
    threads: 12
    resources: tmpdir=/var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T

Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_

Could use some suggestions.
Thanks!

**Comment by Arts-of-coding** [comment]
Good afternoon @sylestiel,

There a number of options to check this without disrupting the run. 

## After or during certain steps
From your current/working directory of anansnake, you can navigate to the folder: /.snakemake/log/
In this folder the log file will contain the processes logged as shown on the command line after the anansnake steps have been completed. 

As an alternative, you can move to your tmpdir, in your case "/var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T" and see when you refresh the directory if and when files have been changed.

To determine this for the conda environment for anansnake directly, you can move to the folder specified after "Activating conda environment", which in your case is: ".snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_". Similarly, you can refresh and see if and when files have been changed.

## Realtime
I suppose the two options above could be insufficient to entirely answer your question since you might want to determine this realtime. To determine if anansnake is actually running, you can run "htop" from your command line (Linux). After running the htop command, you can find the anansnake command under the "Command" column and you can check if the process is running under the "S" column. Within the "S" column, the letter "D" implies that the process is dead (and you are better off with rerunning). The letter "S" stands for sleep that could indicate that either other processes have a higher priority and the program could resume soon. The letter "R" means ready and this is the one you actually want since it indicates that your process is actually running. 

The package [Glances](https://github.com/nicolargo/glances) could be an attractive alternative if you are running our software on Windows. Another option here is to go to Task Manager and try to find the process.

## Other note
Some of the steps from anansnake (and the activation of some of its environments) can run up to several hours until they are finished, so it might be best to leave anansnake running in the background. 

I hope this answers your question. If you have any other anansnake related questions, feel free to ask them here or directly on [anansnake](https://github.com/vanheeringen-lab/anansnake)

**Comment by sylestiel** [comment]
Hi @Arts-of-coding,

Thanks for your wonderful suggestions. 
Unfortunately, htop shows a 'question mark' under the 'S' Column. I tried to disable the 'System Integrity Protection' with a view to determining if the ? represents sleep or running or dead. However, that did not  address the issue.
The log file seems to indicate that it is a hang. 
Is there a way to actually get the scANANSE working?  I even reduced the number of clusters under cluster_id to 2 with 2 contrasts. 
The machine has 64GB of memory and 16 cores despite which there is trouble making it run.

Is there a way to circumvent this issue?

Thank you for your time in advance!

**Comment by Arts-of-coding** [comment]
Hi @sylestiel,

I would suggest to try out your version of our installed package with the sample data that is supplied to the manuscript (see our [Zenodo](https://zenodo.org/record/7575107)). If that works, then it is probably an issue with the configuration for anansnake with your input data. 

Alternatively, you can run the [ example ](https://github.com/vanheeringen-lab/anansnake/tree/master/example) from the anansnake package to test this.

If this is the case you need to check if the config.yaml, rna_samples.tsv and atac_samples.tsv make sense (e.g. check if the correct genome is specified). Additionally, you can check if all your input files contain the correct gene names (uppercase/lowercase or if they are ensembl gene IDs). For anansnake to run, this needs to be identical to each other.

Otherwise, if your currently installed package is not able to run our sample data, I would recommend to reinstall anansnake again into a separate conda environment and try it out again.

Of note, the recommended way to install genomes is through genomepy and make sure that that is the one you install your genome with.

I hope one of these solutions can resolve your issue.

**Comment by sylestiel** [comment]
Hello @Arts-of-coding,

I tried the pbmc sample rds provided and the AnnanseSeurat script.  The trouble is with the anansnake step.

Can you take a look at it and help fix the specific error?

(anansnake) iMac-Pro:anansnake pediatrics$ anansnake --configfile /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/config.yaml --resources mem_mb=48_000 --cores 12
Config
result_dir             : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis
rna_samples            : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/samplefile.tsv
rna_tpms               : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/TPM.tsv
rna_counts             : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/RNA_Counts.tsv
atac_samples           : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/samplefile.tsv
atac_counts            : /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/Peak_Counts.tsv
genome                 : ./scANANSE/data/hg38
database               : gimme.vertebrate.v5.0
jaccard                : 0.1
edges                  : 500000
padj                   : 0.05
plot_type              : png
contrasts              : ['anansesnake_CD4-Naive_average', 'anansesnake_CD4-TCM_average', 'anansesnake_CD8-Naive_average', 'anansesnake_CD16-Mono_average', 'anansesnake_NK_average', 'anansesnake_Treg_average', 'anansesnake_CD14-Mono_average', 'anansesnake_CD8-TCM_average', 'anansesnake_B-intermediate_average', 'anansesnake_cDC2_average', 'anansesnake_B-memory_average', 'anansesnake_CD4-TEM_average', 'anansesnake_MAIT_average', 'anansesnake_CD8-TEM_average', 'anansesnake_B-naive_average', 'anansesnake_gdT_average', 'anansesnake_pDC_average', 'anansesnake_HSPC_average', 'anansesnake_B-naive_B-memory', 'anansesnake_B-memory_B-naive']
tmp_dir                : None

Resources
mem_mb                 : 48000
_cores                 : 12
deseq2                 : 1

Conditions
CD4-Naive              :
  RNA-seq samples:  ['CD4-Naive']
  ATAC-seq samples: ['CD4-Naive']
average                :
  RNA-seq samples:  ['average']
  ATAC-seq samples: ['average']
CD4-TCM                :
  RNA-seq samples:  ['CD4-TCM']
  ATAC-seq samples: ['CD4-TCM']
CD8-Naive              :
  RNA-seq samples:  ['CD8-Naive']
  ATAC-seq samples: ['CD8-Naive']
CD16-Mono              :
  RNA-seq samples:  ['CD16-Mono']
  ATAC-seq samples: ['CD16-Mono']
NK                     :
  RNA-seq samples:  ['NK']
  ATAC-seq samples: ['NK']
Treg                   :
  RNA-seq samples:  ['Treg']
  ATAC-seq samples: ['Treg']
CD14-Mono              :
  RNA-seq samples:  ['CD14-Mono']
  ATAC-seq samples: ['CD14-Mono']
CD8-TCM                :
  RNA-seq samples:  ['CD8-TCM']
  ATAC-seq samples: ['CD8-TCM']
B-intermediate         :
  RNA-seq samples:  ['B-intermediate']
  ATAC-seq samples: ['B-intermediate']
cDC2                   :
  RNA-seq samples:  ['cDC2']
  ATAC-seq samples: ['cDC2']
B-memory               :
  RNA-seq samples:  ['B-memory']
  ATAC-seq samples: ['B-memory']
CD4-TEM                :
  RNA-seq samples:  ['CD4-TEM']
  ATAC-seq samples: ['CD4-TEM']
MAIT                   :
  RNA-seq samples:  ['MAIT']
  ATAC-seq samples: ['MAIT']
CD8-TEM                :
  RNA-seq samples:  ['CD8-TEM']
  ATAC-seq samples: ['CD8-TEM']
B-naive                :
  RNA-seq samples:  ['B-naive']
  ATAC-seq samples: ['B-naive']
gdT                    :
  RNA-seq samples:  ['gdT']
  ATAC-seq samples: ['gdT']
pDC                    :
  RNA-seq samples:  ['pDC']
  ATAC-seq samples: ['pDC']
HSPC                   :
  RNA-seq samples:  ['HSPC']
  ATAC-seq samples: ['HSPC']

Building DAG of jobs...
Creating conda environment ../anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/envs/gimme.yaml...
Downloading and installing remote packages.
Environment for /Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/../envs/gimme.yaml created (location: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_)
Creating conda environment ../anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/envs/ananse.yaml...
Downloading and installing remote packages.
Environment for /Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/../envs/ananse.yaml created (location: .snakemake/conda/2dfbe9ceccde6517ccb9271ef37513a7_)
Using shell: /bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=48000, deseq2=1
Job stats:
job              count    min threads    max threads
-------------  -------  -------------  -------------
all                  1              1              1
binding             19              1              1
deseq2               2              1              1
influence           20              1              1
maelstrom            1             12             12
motif2factors        1             12             12
network             19              1              1
pfmscorefile         1             12             12
plot                20              1              1
total               84              1             12

Select jobs to execute...

[Tue Sep 19 16:42:49 2023]
rule motif2factors:
    input: /Users/pediatrics/anansnake/scANANSE/data/hg38
    output: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38.gimme.vertebrate.v5.0.pfm
    log: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_hg38_m2f.txt
    jobid: 5
    reason: Missing output files: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38.gimme.vertebrate.v5.0.pfm
    threads: 12
    resources: tmpdir=/var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T

Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
[Tue Sep 19 16:43:25 2023]
Finished job 5.
1 of 84 steps (1%) done
Select jobs to execute...

[Tue Sep 19 16:43:25 2023]
rule maelstrom:
    input: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/Peak_Counts.tsv, /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38.gimme.vertebrate.v5.0.pfm, /Users/pediatrics/anansnake/scANANSE/data/hg38
    output: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38-maelstrom
    log: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_hg38_maelstrom.txt
    jobid: 101
    reason: Missing output files: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38-maelstrom; Input files updated by another job: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38.gimme.vertebrate.v5.0.pfm
    threads: 12
    resources: tmpdir=/var/folders/2c/zzjsgs_53vqflzjl28hf1x7r0000gn/T, mem_mb=40000

Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
Activating conda environment: .snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_
### Traceback (most recent call last):
  File "/Users/pediatrics/anansnake/.snakemake/scripts/tmp0a20ao48.maelstrom.py", line 12, in <module>
    import qnorm
  File "/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_/lib/python3.10/site-packages/qnorm/__init__.py", line 2, in <module>
    from .quantile_normalize import quantile_normalize
  File "/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_/lib/python3.10/site-packages/qnorm/quantile_normalize.py", line 6, in <module>
    import numba
  File "/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_/lib/python3.10/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_/lib/python3.10/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_/lib/python3.10/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
[Tue Sep 19 16:43:28 2023]
Error in rule maelstrom:
    jobid: 101
    input: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/Peak_Counts.tsv, /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38.gimme.vertebrate.v5.0.pfm, /Users/pediatrics/anansnake/scANANSE/data/hg38
    output: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/hg38-maelstrom
    log: /Users/pediatrics/Desktop/R_projects/scANANSE/analysis/gimme/log_hg38_maelstrom.txt (check log file(s) for error message)
    conda-env: /Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_

RuleException:
CalledProcessError in line 80 of /Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/gimme.smk:
Command 'source /Users/pediatrics/anaconda3/envs/anansnake/bin/activate '/Users/pediatrics/anansnake/.snakemake/conda/3f88efe941f72bcdb4d5867b0d6db92f_'; set -euo pipefail;  python /Users/pediatrics/anansnake/.snakemake/scripts/tmp0a20ao48.maelstrom.py' returned non-zero exit status 1.
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/site-packages/anansnake/rules/gimme.smk", line 80, in __rule_maelstrom
  File "/Users/pediatrics/anaconda3/envs/anansnake/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-09-19T163816.823131.snakemake.log

**Comment by sylestiel** [comment]
Thanks!
