### ISSUE TITLE
Organizational questions pertaining to installation

### ISSUE THREAD

**Issue by sylestiel** [JGASmits/AnanseSeurat#32]
Hi @Arts-of-coding and @JGASmits,

1) Where should the s scANANSE/analysis and scANANSE/data folders reside with respect to anansnake?
2) Am I required to run the following 2 commands within the anansanke folder:
             wget https://raw.githubusercontent.com/JGASmits/AnanseSeurat/main/inst/scANANSE.yml
               and conda env create -f scANANSE.yml 

3) Do I have to modify the scANANSE.yml for mouse genotype?

4) I plan to use the PBMC preprocessed.rds  using the AnanseSeurat script provided in https://f1000research.com/articles/12-243

     I appear to run into issues  when trying to run 
anansnake --configfile scANANSE/analysis/config.yaml --resources mem_mb=48_000 --cores 12

I would appreciate any feedback from your end since I've been at this for a while.

Thank you!

**Comment by JGASmits** [comment]
Dear Sylestiel,

Hopefully i can be of help! My response times are a bit slower due to starting a new job. Regarding your points:

1. You can specify the locations of the analysis folder and the data folder when running scANANSE. The location shoeldnt matter as long as you specify it correctly when generating the config files for Anansnake (in the config_scANANSE step). If however you are thinking you are perhaps referencing the files wrong somewhere, you can always default to the proposed structure mentioned int he F1000 manuscript (under part1 installation and setup) https://f1000research.com/articles/12-243. 

2. This command generates the conda environment needed to run scANANSE, it includes installing R, Seurat and some other pacakges. The location of where you run it doesnt matter, the environment created is the important part. Your own R environment with scANANSE should work the same to that one, but when experience problems using that one makes sure there shouldnt be installation problems.

3. Since you are experiencing these difficulties, i would first make sure it works with human data on your machine. After this works modifying it to mouse should be a matter of changing the genome (installed with genomepy) and changing the genomename specified in the config_scANANSE step.

4. I would double check both the filelocations are correct in the config file, and the files generated look like expected (for examples on how they should look like see the F1000 paper), i would try downscaling the ammount of cores to see if that help.

Gr JGA Smits

**Comment by sylestiel** [comment]
Dear @JGASmits,

Thank you for your detailed response to my questions despite the time crunch. It is very helpful.
